steps:
  - id: build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_IMAGE}:${SHORT_SHA}
      - -t
      - ${_IMAGE}:latest
      - .

  - id: push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - --all-tags
      - ${_IMAGE}

  - id: deploy
    name: gcr.io/google.cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image=${_IMAGE}:${SHORT_SHA}
      - --region=${_REGION}
      - --platform=managed
      - --execution-environment=gen2
      - --memory=1Gi
      - --cpu=1
      - --timeout=900
      - --concurrency=20
      - --min-instances=0
      - --max-instances=5
      - --port=8080
      - --allow-unauthenticated

images:
  - ${_IMAGE}:${SHORT_SHA}
  - ${_IMAGE}:latest

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE_NAME: ttt-api
  _REGION: europe-west2
  _IMAGE: europe-west2-docker.pkg.dev/${PROJECT_ID}/backend/ttt-api
